# .github/workflows/cicd.yml
name: CI/CD Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_push: # Rename job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub (only needed for pushing)
      - name: Login to Docker Hub 
        # Only run this step on pushes to main, not on pull requests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        id: build # Give this step an id to reference its output
        run: |
          IMAGE_TAG=sha-${{ github.sha }}
          # If push to main, also tag as latest
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="--tag ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-project:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-project:${IMAGE_TAG}"
          else
            TAGS="--tag ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-project:${IMAGE_TAG}"
          fi
          docker build $TAGS .
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT # Make tag available to later steps

      # --- Basic Test --- (same as before)
      - name: Run container for a basic check
        run: |
          docker run -d --rm -p 5000:5000 --name test-app ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-project:sha-${{ github.sha }}
          sleep 5 
          curl -f http://localhost:5000 || exit 1 
          docker stop test-app

      # Push the Docker image to Docker Hub
      - name: Push image to Docker Hub
        # Only run this step on pushes to main, not on pull requests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-project:sha-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-devops-project:latest